version: '3'

services:
  ci-test-server:
    build: ci-test-server
    volumes:
      - ../dev-server:/var/server/
      - ../development:/var/development
    ports:
      - 8000
    entrypoint:
      - node
      - /var/server/ci-server.js
  jest-image-snapshot:
    image: navikt/docker-jest-image-snapshot:1.0.0
    depends_on:
      - ci-test-server
    volumes:
      - ./jest-image-snapshot/tests:/app/tests
      - ./jest-image-snapshot/baseline:/app/baseline
      - ./reports:/app/reports